package greendao_three;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_MAGESS".
*/
public class User_magessDao extends AbstractDao<User_magess, Long> {

    public static final String TABLENAME = "USER_MAGESS";

    /**
     * Properties of entity User_magess.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, int.class, "User_id", false, "User_id");
        public final static Property User_magess = new Property(2, String.class, "User_magess", false, "User_magess");
    }


    public User_magessDao(DaoConfig config) {
        super(config);
    }
    
    public User_magessDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_MAGESS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"User_id\" INTEGER NOT NULL ," + // 1: User_id
                "\"User_magess\" TEXT);"); // 2: User_magess
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_MAGESS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User_magess entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
 
        String User_magess = entity.getUser_magess();
        if (User_magess != null) {
            stmt.bindString(3, User_magess);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User_magess entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
 
        String User_magess = entity.getUser_magess();
        if (User_magess != null) {
            stmt.bindString(3, User_magess);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User_magess readEntity(Cursor cursor, int offset) {
        User_magess entity = new User_magess( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // User_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // User_magess
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User_magess entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.getInt(offset + 1));
        entity.setUser_magess(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User_magess entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User_magess entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User_magess entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
